language:
  ruby

rvm:
  - '1.9.3'
  - '2.0.0'
  - '2.1.1'

script:
  bundle exec rake test
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev r-base r-base-dev
  - sudo R 
  - sudo Rscript -e "install.packages(c('Rserve','irr'),,'http://cran.us.r-project.org')"
